/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jom (https://sketchfab.com/jom239300891)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/magic-book-628b850d708f4b858ae0b2615bb39ce0
title: Magic Book
*/

import { useRef, Suspense } from 'react';
import { useGLTF } from '@react-three/drei';

function Book(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/magic-book/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/magic-book/scene.gltf');

const MagicBookModel = () => {
  const meshRef = useRef();

  // useFrame(({ gl }) => {
  //   if (meshRef && meshRef.current) {
  //     meshRef.current.scale.set(0.8, 0.8, 0.8);
  //     // meshRef.current.rotation.y += 0.01;
  //   }
  // });

  return (
    <>
      <mesh
        ref={meshRef}
        castShadow
        scale={[0.8, 0.8, 0.8]}
        position={[40, 0, 0]}
      >
        <Suspense fallback={null}>
          <Book />
        </Suspense>
      </mesh>
    </>
  );
};

export default MagicBookModel;
